### PR TITLE
Contribution Clarifications

### PR DESCRIPTION
**Pull request by FinnHornhoover**

### CODE REVIEW

**Comment by FinnHornhoover** [comment]
Should this be a separate file instead?

**Comment by CakeLancelot** [comment]
It seems the standard (according to Github at least) is to have a CONTRIBUTING.md in the main directory, maybe move this paragraph there and link it from the README?

**Comment by dongresource** [comment]
I am against this change for two reasons:
* I really don't think we need more inexperienced developers, especially if they would need step-by-step instructions to learn the basics of git.
* The instructions in this PR are bad advice (especially 7.) and will lead to more of the exact same problem we see with the commits in this PR  (no offense, of course).

Teaching people the basics how to use git is way out of scope for this project and we really don't need more minimum-experience contributors. They would only bog the project down at this point. We should instead focus on helping our existing contributors improve.

If we're going to add a CONTRIBUTING.md file, I think it would be a much better idea to have it try and hone the git-fu of our current contributors and explain why their repositories are getting riddled with meaningless merge commits as well as supply links to pages like https://git-rebase.io/ and http://think-like-a-git.net/ that will help solve that issue.

I'll gladly write that myself, if you want?

**Comment by FinnHornhoover** [comment]
@dongresource Sure. I'm closing this down then, since there'll be a new PR on the way.

**Pull request closed without merging**
